package main

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger" // echo-swagger middleware

	_ "switcher-api/docs" // docs is generated by Swag CLI, you have to import it.
)

func main() {
	// Create a new Echo instance
	echoInstance := echo.New()

	// Define routes
	defineRoutes(echoInstance)

	// Serve Swagger docs
    echoInstance.GET("/swagger/*", echoSwagger.WrapHandler)

	// Start the server
	echoInstance.Logger.Fatal(echoInstance.Start(":8080"))
}

// defineRoutes sets up the routes for the Echo instance
func defineRoutes(e *echo.Echo) {
	e.GET("/", rootHandler)
	e.POST("/switch/:id", updateSwitchHandler)
	e.GET("/switch/:id", getSwitchHandler)
}

// rootHandler handles the root URL
func rootHandler(c echo.Context) error {
	//TODO: Implement root logic here
	isTls := c.IsTLS()
	return c.String(http.StatusOK, fmt.Sprintf("Is TLS: %v", isTls))
}

// updateSwitchHandler handles the update switch request
func updateSwitchHandler(c echo.Context) error {
	//TODO: Implement update logic here
	return c.String(http.StatusOK, "Switch updated")
}

// getSwitchHandler handles the get switch request
func getSwitchHandler(c echo.Context) error {
	//TODO: Implement get logic here
	return c.String(http.StatusOK, "Switch details")
}